library(orderly)
library(orderly.sharepoint)
library(naomi)
library(naomi.utils)
library(rdhs)
library(tidyverse)
library(sf)

orderly_pull_archive(tolower("AGO_data_areas"), remote="naomi_2021")
orderly_pull_archive(tolower("BEN_data_areas"), remote="naomi_2021")
orderly_pull_archive(tolower("CAF_data_areas"), remote="naomi_2021")
orderly_pull_archive(tolower("COG_data_areas"), remote="naomi_2021")
orderly_pull_archive(tolower("GAB_data_areas"), remote="naomi_2021")
orderly_pull_archive(tolower("GMB_data_areas"), remote="naomi_2021")
orderly_pull_archive(tolower("LBR_data_areas"), remote="naomi_2021")
orderly_pull_archive(tolower("MLI_data_areas"), remote="naomi_2021")
orderly_pull_archive(tolower("NER_data_areas"), remote="naomi_2021")
orderly_pull_archive(tolower("TCD_data_areas"), remote="naomi_2021")

orderly::orderly_pull_archive("aaa_data_population_worldpop", remote = "naomi_2021", id = 'latest(parameter:iso3 == "AGO")')
orderly::orderly_pull_archive("aaa_data_population_worldpop", remote = "naomi_2021", id = 'latest(parameter:iso3 == "BEN")')
orderly::orderly_pull_archive("aaa_data_population_worldpop", remote = "naomi_2021", id = 'latest(parameter:iso3 == "CAF")')
orderly::orderly_pull_archive("aaa_data_population_worldpop", remote = "naomi_2021", id = 'latest(parameter:iso3 == "COG")')
orderly::orderly_pull_archive("aaa_data_population_worldpop", remote = "naomi_2021", id = 'latest(parameter:iso3 == "GAB")')
orderly::orderly_pull_archive("aaa_data_population_worldpop", remote = "naomi_2021", id = 'latest(parameter:iso3 == "GMB")')
orderly::orderly_pull_archive("aaa_data_population_worldpop", remote = "naomi_2021", id = 'latest(parameter:iso3 == "LBR")')
orderly::orderly_pull_archive("aaa_data_population_worldpop", remote = "naomi_2021", id = 'latest(parameter:iso3 == "MLI")')
orderly::orderly_pull_archive("aaa_data_population_worldpop", remote = "naomi_2021", id = 'latest(parameter:iso3 == "NER")')
orderly::orderly_pull_archive("aaa_data_population_worldpop", remote = "naomi_2021", id = 'latest(parameter:iso3 == "TCD")')

orderly_new("caf_survey")
