remote:
  real:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/naomi-data-orderly
  mics:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/mics
  fertility:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/fertility

global_resources:
  global