remote:
  main:
    driver: orderlyweb::orderlyweb_remote
    args:
      host: hiv-orderly.dide.ic.ac.uk
      port: 443
      prefix: fertility
      token: $ORDERLYWEB_GITHUB_TOKEN
    primary: true
    default_branch: master 
    default_branch_only: true
  inference-web:
    driver: orderlyweb::orderlyweb_remote
    args:
      host: hiv-orderly.dide.ic.ac.uk
      port: 443
      prefix: inference-data
      token: $ORDERLYWEB_GITHUB_TOKEN
    # primary: true
    default_branch: main  
  fertility-sharepoint:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/fertility

  # real:
  #   driver: orderly.sharepoint::orderly_remote_sharepoint
  #   args:
  #     url: https://imperiallondon.sharepoint.com
  #     site: HIVInferenceGroup-WP
  #     path: Shared Documents/orderly/naomi-data-orderly

  naomi_2021:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/naomi-orderly-naomi2
  # mics:
  #   driver: orderly.sharepoint::orderly_remote_sharepoint
  #   args:
  #     url: https://imperiallondon.sharepoint.com
  #     site: HIVInferenceGroup-WP
  #     path: Shared Documents/orderly/mics
  malawi:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/mwi-hiv-orderly
  kp:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/kp-data

vault:
  addr: https://vault.dide.ic.ac.uk:8200
  
global_resources:
  global
